name: gh-pages

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
        
      - run: npm i
      # - run: npm run prepublish
      - run: cp ./mammoth.browser.js ./browser-demo/mammoth.browser.js

      - name: deploy
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./browser-demo

  # deploy:
  #   name: deploy
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - name: deploy
  #       if: github.event_name == 'push'
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./browser-demo